In [3]:
import numpy as np
import pandas as pd

In [25]:
value=np.array([1,2,5,6])
weights=np.array([2,3,4,5])
Wmax=8




In [92]:
def dpk(value,weights,Wmax): #obj for rows,wi for columns
    profits=np.zeros((len(weights)+1,Wmax+1),int) #create empty 2d array
    print(profits)
    for obj in range(len(weights)+1):
        for wi in range(Wmax+1):
            if obj==0 or wi==0:
                profits[obj][wi]=0
           
            elif weights.loc[obj-1]<=wi:
                profits[obj][wi]=max(profits[obj-1][wi],value.loc[obj-1]+profits[obj-1][wi-weights.loc[obj-1]])
            else:
                profits[obj][wi]=profits[obj-1][wi]
                
    return profits[len(weights)][Wmax]
                
            
            

In [66]:
#print(dpk(value,weights,Wmax))

In [90]:
df=pd.read_csv('./Downloads/input.csv')
print(df.head(7))
print(df['weight'].loc[1])

   object  profit  weight
0       1       5       1
1       2      10       3
2       3      15       5
3       4       7       4
4       5       8       1
5       6       9       3
6       7       4       2
3


In [93]:
dpk(df['profit'],df['weight'],15)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


51